name: Spy

on:
  issue_comment:
      types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:      
      - uses: actions/github-script@v3
        id: get_round
        with:
         result-encoding: string
         script: |
           const asso = context.payload.comment.author_association
           if(asso == 'OWNER' || asso == 'COLLABORATOR') {
             const body = context.payload.comment.body
             if(body.includes("build:")) {
               return body.replace('build:','')
             }
           }
           return 'stop'

      - uses: actions/github-script@v3
        if: steps.get_round.outputs.result != 'stop'
        id: get_pr_branch
        with:
         result-encoding: string
         script: |
           //get pullrequest url
           const pr_number = context.payload.issue.number
           //get upstream branch
           const pr = await github.pulls.get({
                owner: "maxGimeno",
                repo: "docker_tests",
                pull_number: pr_number,
           });
           const result = pr.data.head.label
           return result.replace(/(.*):(.*)/, '$2')
      - uses: actions/checkout@v2
        name: "checkout branch"
        if: steps.get_round.outputs.result != 'stop'
        with:
          repository: maxGimeno/docker_tests
          ref: ${{ steps.get_pr_branch.outputs.result }}
          token: ${{ secrets.TOKEN_FOR_CHECKOUT }}
          
      - name: Post address
        uses: actions/github-script@v3
        if: steps.get_round.outputs.result != 'stop'
        with:
          script: |
            const pr_number = context.payload.issue.number
            github.issues.createComment({
              owner: "maxGimeno",
              repo: "docker_tests",
              issue_number: pr_number,
              body: "test"
            });
      
