name: Spy

on:
  pull_request_target:
    types: [edited]
  issue_comment:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
      id: check
      with:
       script: |
          console.log(context.payload.comment.body)
          
          
