name: Spy

on:
  issue_comment:
      types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:      
      - uses: actions/github-script@v3
        id: check
        with:
         script: |
           const asso = context.payload.comment.author_association
           if(asso == 'OWNER' || asso == 'COLLABORATOR') {
             const body = context.payload.comment.body
             if(body.includes("build:")) {
               console.log(body.replace('build:',''))
               //get pullrequest url
               console.log(context.payload.issue)
               const pr_number = context.payload.issue.pull_request.number
               //get upstream branch
               const opts = await github.pulls.get({
                    owner: "maxGimeno",
                    repo: "docker_tests",
                    pull_number: pr_number,
               });
               console.log(opts)
             }
           }
