name: Spy

on:
  issue_comment:
      types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:      
      - uses: actions/github-script@v3
        id: get_round
        with:
         result-encoding: string
         script: |
           const asso = context.payload.comment.author_association
           if(asso == 'OWNER' || asso == 'COLLABORATOR') {
             const body = context.payload.comment.body
             if(body.includes("build:")) {
               return body.replace('build:','')
             }
           }
           return 'stop'

      - uses: actions/github-script@v3
        if: steps.get_round.outputs.result != 'stop'
        id: get_pr_number
        with:
         result-encoding: string
         script: |
           //get pullrequest url
           const pr_number = context.payload.issue.number
           return pr_number
           
      - name: Post address
        uses: actions/github-script@v3
        if: steps.get_round.outputs.result != 'stop'
        with:
          script: |
            const pr_number = context.payload.issue.number
            const address = "The documentation is built. You can find it here : https://cgal.github.io/${{ steps.get_pr_number.outputs.result }}/${{ steps.get_round.outputs.result }}/Manual/index.html"
            github.issues.createComment({
              owner: "maxGimeno",
              repo: "docker_tests",
              issue_number: pr_number,
              body: address
            });
      
