name: Spy

on:
  issue_comment:
      types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:      
      - uses: actions/github-script@v3
        id: check
        with:
         script: |
           const asso = context.payload.comment.author_association
           if(asso == 'OWNER' || asso == 'COLLABORATOR') {
             const body = context.payload.comment.body
             if(body.includes("build:")) {
               console.log(body.replace('build:',''))
               //get pullrequest url
               const url = context.payload.issue.pull_request.url
               //get upstream branch
               console.log(github.pulls)               
             }
           }
