name: Spy

on:
  issue_comment:
      types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:      
      - uses: actions/github-script@v3
        id: check
        with:
         script: |
           console.log(context.payload)
            const body = context.payload.comment.body
            if(body.includes("build:")) {
              console.log(body.replace('build:',''))
            }
          
